# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base}]

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0}]

# IP: bd/base/ip/base_axi_gpio_0_0/base_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_0 || ORIG_REF_NAME==base_axi_gpio_0_0}]

# IP: bd/base/ip/base_ps7_0_axi_periph_0/base_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_ps7_0_axi_periph_0}]

# IP: bd/base/ip/base_rst_ps7_0_100M_0/base_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_100M_0 || ORIG_REF_NAME==base_rst_ps7_0_100M_0}]

# IP: bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_dma_0_0 || ORIG_REF_NAME==base_axi_dma_0_0}]

# IP: bd/base/ip/base_xbar_0/base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0}]

# IP: bd/base/ip/base_axi_mem_intercon_0/base_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_0 || ORIG_REF_NAME==base_axi_mem_intercon_0}]

# IP: bd/base/ip/base_axi_mem_intercon_1_0/base_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_1_0 || ORIG_REF_NAME==base_axi_mem_intercon_1_0}]

# IP: bd/base/ip/base_Conv_0_0/base_Conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_Conv_0_0 || ORIG_REF_NAME==base_Conv_0_0}]

# IP: bd/base/ip/base_axi_mem_intercon_2_0/base_axi_mem_intercon_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_2_0 || ORIG_REF_NAME==base_axi_mem_intercon_2_0}]

# IP: bd/base/ip/base_Pool_0_0/base_Pool_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_Pool_0_0 || ORIG_REF_NAME==base_Pool_0_0}]

# IP: bd/base/ip/base_axi_mem_intercon_3_0/base_axi_mem_intercon_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_mem_intercon_3_0 || ORIG_REF_NAME==base_axi_mem_intercon_3_0}]

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0}]

# IP: bd/base/ip/base_auto_pc_1/base_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_1 || ORIG_REF_NAME==base_auto_pc_1}]

# IP: bd/base/ip/base_auto_us_0/base_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_0 || ORIG_REF_NAME==base_auto_us_0}]

# IP: bd/base/ip/base_auto_pc_2/base_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_2 || ORIG_REF_NAME==base_auto_pc_2}]

# IP: bd/base/ip/base_auto_us_1/base_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_1 || ORIG_REF_NAME==base_auto_us_1}]

# IP: bd/base/ip/base_auto_pc_3/base_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_3 || ORIG_REF_NAME==base_auto_pc_3}]

# IP: bd/base/ip/base_auto_us_2/base_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_2 || ORIG_REF_NAME==base_auto_us_2}]

# IP: bd/base/ip/base_auto_pc_4/base_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_4 || ORIG_REF_NAME==base_auto_pc_4}]

# IP: bd/base/ip/base_auto_us_3/base_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_us_3 || ORIG_REF_NAME==base_auto_us_3}]

# XDC: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0}] {/inst }]/inst ]]

# XDC: bd/base/ip/base_axi_gpio_0_0/base_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_0 || ORIG_REF_NAME==base_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base/ip/base_axi_gpio_0_0/base_axi_gpio_0_0_ooc.xdc

# XDC: bd/base/ip/base_axi_gpio_0_0/base_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_0 || ORIG_REF_NAME==base_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base/ip/base_rst_ps7_0_100M_0/base_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_100M_0 || ORIG_REF_NAME==base_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/base/ip/base_rst_ps7_0_100M_0/base_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_100M_0 || ORIG_REF_NAME==base_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/base/ip/base_rst_ps7_0_100M_0/base_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_ooc.xdc

# XDC: bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_dma_0_0 || ORIG_REF_NAME==base_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base/ip/base_axi_dma_0_0/base_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_dma_0_0 || ORIG_REF_NAME==base_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base/ip/base_xbar_0/base_xbar_0_ooc.xdc

# XDC: bd/base/ip/base_Conv_0_0/constraints/Conv_ooc.xdc

# XDC: bd/base/ip/base_Pool_0_0/constraints/Pool_ooc.xdc

# XDC: bd/base/ip/base_auto_pc_0/base_auto_pc_0_ooc.xdc

# XDC: bd/base/ip/base_auto_pc_1/base_auto_pc_1_ooc.xdc

# XDC: bd/base/ip/base_auto_us_0/base_auto_us_0_ooc.xdc

# XDC: bd/base/ip/base_auto_us_0/base_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_0 || ORIG_REF_NAME==base_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/base/ip/base_auto_pc_2/base_auto_pc_2_ooc.xdc

# XDC: bd/base/ip/base_auto_us_1/base_auto_us_1_ooc.xdc

# XDC: bd/base/ip/base_auto_us_1/base_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_1 || ORIG_REF_NAME==base_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/base/ip/base_auto_pc_3/base_auto_pc_3_ooc.xdc

# XDC: bd/base/ip/base_auto_us_2/base_auto_us_2_ooc.xdc

# XDC: bd/base/ip/base_auto_us_2/base_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_2 || ORIG_REF_NAME==base_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/base/ip/base_auto_pc_4/base_auto_pc_4_ooc.xdc

# XDC: bd/base/ip/base_auto_us_3/base_auto_us_3_ooc.xdc

# XDC: bd/base/ip/base_auto_us_3/base_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_auto_us_3 || ORIG_REF_NAME==base_auto_us_3}] {/inst }]/inst ]]

# XDC: bd/base/base_ooc.xdc
